baseurl = "https://www.cesardelsolar.com"
languageCode = "en-us"
title = "César Del Solar, Maker of Things"
disqusShortname = "https-www-cesardelsolar-com"
enableRobotsTXT = true
enableGitInfo = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[pagination]
  pagerSize = 9

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"
  background_color_class = "bg-blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = true

  # center theme with default width
  centerTheme = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false
  favicon = "/images/favicon.ico"

[[params.social]]
    name = "github"
    url = "https://github.com/domino14"

[markup.goldmark.renderer]
  unsafe = true

[module]
[[module.imports]]
  disable = false
  ignoreConfig = false
  ignoreImports = false
  path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'