baseurl = "https://www.cesardelsolar.com"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
paginate = 10
title = "César Del Solar, Maker of Things"
disqusShortname = "cesardelsolar"

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"
  background_color_class = "bg-blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = true

  # center theme with default width
  centerTheme = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false
  favicon = "/images/favicon.ico"

  [[params.ananke_socials]]
    name = "twitter"
    url = "https://twitter.com/14domino"
  [[params.ananke_socials]]
    name = "github"
    url = "https://github.com/domino14"

[markup.goldmark.renderer]
  unsafe = true
# [languages]
#   [languages.en]
#     languageName = "English"
#     title = "César Del Solar"
#     subtitle = "Maker of things"
#     owner = ""
#     keywords = ""
#     copyright = "César Del Solar"
#     menuMore = "Show more"
#     readMore = "Read more"
#     readOtherPosts = "Read other posts"
#     missingContentMessage = "Page not found..."
#     missingBackButtonLabel = "Back to home page"

#     [languages.en.params.logo]
#       logoText = "Terminal"
#       logoHomeLink = "/"

#     [languages.en.menu]
#       [[languages.en.menu.main]]
#         identifier = "about"
#         name = "About"
#         url = "/about"
#       [[languages.en.menu.main]]
#         identifier = "showcase"
#         name = "Showcase"
#         url = "/showcase"
